name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: ${{ matrix.group }} - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        group:
          - Basic
        version:
          - '1.6'
          - '1'
          #- 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: cjdoris/julia-downgrade-compat-action@v1
        if: ${{ matrix.version == '1.6' }}
        with:
          skip: Pkg,TOML,Statistics          
      - run:
          julia -e '
          using Pkg;
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General"));'
          # allow RegistryTw julia registry
          #Pkg.Registry.add(RegistrySpec(url = "https://github.com/bgctw/RegistryTw.git"))
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        env:
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - run:
          julia -e '
          using Pkg;
          Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General"));'
          # register RegistryTw julia registry
          # Pkg.Registry.add(RegistrySpec(url = "https://github.com/bgctw/RegistryTw.git"))
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: DocMeta, doctest
            using DistributionVectors
            DocMeta.setdocmeta!(DistributionVectors, :DocTestSetup, :(using DistributionVectors); recursive=true)
            doctest(DistributionVectors)'
      - run: julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
